name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    env:
      SOLUTION_NAME: NickJohn.WinUI.ObservableSettings.sln
      PACKAGE_PROJECT_NAME: NickJohn.WinUI.ObservableSettings
      TEST_PROJECT_NAME: NickJohn.WinUI.ObservableSettings.Test

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Add VSTest to PATH
      uses: darenm/Setup-VSTest@v1.2

    - name: Restore dependencies
      run: dotnet restore $env:SOLUTION_NAME

    - name: Build solution
      run: |
        msbuild $env:SOLUTION_NAME `
          /p:Configuration=${{ matrix.configuration }} `
          /p:Platform=${{ matrix.platform }}

    - name: 🧪 Unit testing
      run: |
        vstest.console.exe test\${env:TEST_PROJECT_NAME}\bin\${{ matrix.platform }}\${{ matrix.configuration }}\*\${env:TEST_PROJECT_NAME}.build.appxrecipe
